config/routes.rb
PocApp::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :sessions => :sessions, :confirmations => :confirmations }

  devise_scope :user do
    put "password/:scope", :to => "devise/passwords#update", :as => :update_password
    get '/password/breach/:token' => 'passwords#breach', :as => :password_breach
  end

  resources :profiles, :only => [:edit, :update, :show] do
    member do
      get :edit_image
      post :update_image
      delete :remove_avatar
    end
    resources :experiences do
      member do
        get :remove
      end
    end
    resources :certificates do
      member do
        get :remove
        delete :remove_attachment
        get :preview
      end
    end
    resources :educations do
      member do
        get :remove
      end
    end
    resources :skills, :only => [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :emails do
      member do
        post :make_primary
      end
      collection do
        get  :confirmation
        get  :breach
      end
    end
  end

  resources :suggestions, :only => [:index]
  resources :recruiters do
    collection do
      get :confirmation
    end
  end

  resources :recruiter_sessions, :only => [:new, :create]
  resources :accounts

  resources :searches
  resources :jobs
  resources :manage_pages do
    collection do
      get :require_authentication
      get :authenticate
      get :facebook
      get :redirect_from_facebook
      get :twitter
      get :twitter_callback
    end
  end

  match 'email_validation' => 'main#email_validation', :via => :get, :as => "email_validation"
  match 'social/:action', :via => :get, :to => "social#integration", :as => :social
  match 'profiles/:profile_id/:id', :via => :get, :to => "profiles#extra", :as => :profile_extra
  match 'main/:action', :via => [:get, :post], :to => "main#extra", :as => :extras
  match 'images/upload_image', :via => [:post], :to => "images#upload_image", :as => :upload_image
  match 'login', :via => [:get], :to => "main#login", :as => :login
  match 'signup', :via => [:get], :to => "main#signup", :as => :signup
  match 'forgot_password', :via => [:get], :to => "main#forgot_password", :as => :forgot_password
  match 'confirmation_instructions', :via => [:get], :to => "main#confirmation_instructions", :as => :confirmation_instructions

  get '/activities(.:format)' => 'main#activities', :as => :activities
  get '/:page' => 'main#show', :as => :page

  root :to => 'accounts#index'

end

app/models/skill.rb
class Skill

  include Mongoid::Document

  field :user_id, type: Integer
  field :name, type: String

  belongs_to :user

end

app/helpers/skills_helper.rb
module SkillsHelper

  def user_skills
    @user.skills.collect(&:name).join(",")
  end

end

app/views/skills/_form.html.erb
<%= form_tag(profile_skills_path(@user), :remote => true, :method => :post) do %>

  <div style="margin-top: 20px">
    <div class="name input-group col-md-5">
      <%= text_field_tag "skills", "", :spellcheck => true, :class => "form-control" %>
    </div>
    <button id="addtag" class="btn btn-primary btn-lg" >Add</button>
    <div class="clearfix"></div>
    <%= text_field_tag "tags", user_skills %>
  </div>
  <div class="saveCancel">
    <div class="inner">
      <%= link_to "Cancel",  "#", :onclick => 'location.reload();', :class => "btn btn-primary btn-lg"  %>
      <%= submit_tag "Save", :class => "btn btn-primary btn-lg" %>
    </div>
  </div>

<% end %>

app/views/skills/_skills.html.erb
<div class="skill-index">
  <div class="pull-left span8 col-md-12">
    <div class="pull-left"><h3><i class="fa fa-wrench fa-1x"></i>
      <span>Skills &amp; Expertise</span></h3></div>
    <div class="pull-right">
      <%= link_to '<i class="fa fa-plus"></i> Add Skill'.html_safe, edit_profile_skills_path(@user), 
       :class => "add-skills-colorbox", :id => "add-skills-colorbox" %>
      
    </div>
  </div>
  <div class="clearfix"></div>
  <ul class="col-md-12">
    <div class="skills">
      <input type="text" id="completed_tags" value="<%= @user.skills.collect(&:name).join(",") %>"  />
    </div>
    <div class="skills-form">
      <%= render "form" %>
    </div>
  </ul>

</div>

app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<div class="profile">
  <div class="header"><%= render :partial => 'profiles/header' %></div>
  <div class="left-container col-lg-3">
    <div class="user-img">
      <h4><%= @user.name %></h4>
      <%= render :partial => 'profiles/position' %>
    </div>
    <div class="details">
      <div class="clearfix"></div>
      <% unless recruiter? %>
        <div class="incomplete"><%= profile_completeness_prompt %></div>
      <% end %>
      <div class="clearfix"></div>
      <div class="pull-left span4"><%= render :partial => 'profiles/navigation' %></div>
    </div>
  </div>
  <div class="right-container col-lg-9">
    <%= render :partial => 'profiles/current_position' %>
    <div class="pull-right"><%= render :partial => 'profiles/menu' %></div>
    <div class="forms"><%= render :partial => 'skills' %></div>
  </div>
</div>

app/views/skills/index.js.erb
function has_text(iteration, text){
  content = $(iteration).map(function(){
    return $(this).text().replace(/\s/g, '').toLowerCase()
  })
  return  $.inArray(text.toLowerCase(),content) >= 0
}
$(".forms").html("<%= raw escape_javascript(render :partial => 'skills/skills') %>")
$("#skills").autocomplete(
{
  source: "/suggestions?from=Skill&for=name"
})
$('#tags').tagsInput()
  $('#completed_tags').tagsInput()
$('#addtag').click(function(){
  if($(".skills-form .tag span").length < 36 && $('#skills').val().replace(/\s/g, '') != '' && !has_text($(".tag span"), $('#skills').val().replace(/\s/g, '')))
  {
    $('#tags').addTag($("#skills").val().replace(/\s/g, ''));
  }
  $('#skills').val('')
  return false
})
$("#add-skills-colorbox").click(function(e){
  $(".skills-form").toggle()
  $(".skills").toggle()
  e.preventDefault()
  return false
})

app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @skill.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @skill.name %>
</p>


<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

app/views/skills/update.js.erb
location.href = "<%= profile_extra_path(@user, 'skills') %>"