config/routes.rb
PocApp::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :sessions => :sessions, :confirmations => :confirmations }

  devise_scope :user do
    put "password/:scope", :to => "devise/passwords#update", :as => :update_password
    get '/password/breach/:token' => 'passwords#breach', :as => :password_breach
  end

  resources :profiles, :only => [:edit, :update, :show] do
    member do
      get :edit_image
      post :update_image
      delete :remove_avatar
    end
    resources :experiences do
      member do
        get :remove
      end
    end
    resources :certificates do
      member do
        get :remove
        delete :remove_attachment
        get :preview
      end
    end
    resources :educations do
      member do
        get :remove
      end
    end
    resources :skills, :only => [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :emails do
      member do
        post :make_primary
      end
      collection do
        get  :confirmation
        get  :breach
      end
    end
  end

  resources :suggestions, :only => [:index]
  resources :recruiters do
    collection do
      get :confirmation
    end
  end

  resources :recruiter_sessions, :only => [:new, :create]
  resources :accounts

  resources :searches
  resources :jobs
  resources :manage_pages do
    collection do
      get :require_authentication
      get :authenticate
      get :facebook
      get :redirect_from_facebook
      get :twitter
      get :twitter_callback
    end
  end

  match 'email_validation' => 'main#email_validation', :via => :get, :as => "email_validation"
  match 'social/:action', :via => :get, :to => "social#integration", :as => :social
  match 'profiles/:profile_id/:id', :via => :get, :to => "profiles#extra", :as => :profile_extra
  match 'main/:action', :via => [:get, :post], :to => "main#extra", :as => :extras
  match 'images/upload_image', :via => [:post], :to => "images#upload_image", :as => :upload_image
  match 'login', :via => [:get], :to => "main#login", :as => :login
  match 'signup', :via => [:get], :to => "main#signup", :as => :signup
  match 'forgot_password', :via => [:get], :to => "main#forgot_password", :as => :forgot_password
  match 'confirmation_instructions', :via => [:get], :to => "main#confirmation_instructions", :as => :confirmation_instructions

  get '/activities(.:format)' => 'main#activities', :as => :activities
  get '/:page' => 'main#show', :as => :page

  root :to => 'accounts#index'

end

app/helpers/experiences_helper.rb
module ExperiencesHelper

  def end_date_of(experience)
    experience.current ? "Present" : experience_date(experience.end_date)
  end

  def experience_date(date)
    date.strftime("%B %Y")
  end

  def duration_for_experience(experience)
    start_date = experience.start_date
    if experience.current
      end_date = Time.current
    else
      end_date = experience.end_date
    end
    time_diff_components = Time.diff(start_date, end_date, '%y, %M')
    time_diff_components[:diff]
  end

  def remove_experience_link
    link_to remove_profile_experience_path(@user, @experience) do
      content_tag(:i, "", :class => "fa fa-trash-o fa-2x")
    end.html_safe
  end

  def remove_certificate_link
    link_to remove_profile_certificate_path(@user, @certificate) do
      content_tag(:i, "", :class => "fa fa-trash-o fa-2x")
    end.html_safe
  end

  def remove_education_link
    link_to remove_profile_education_path(@user, @education) do
      content_tag(:i, "", :class => "fa fa-trash-o fa-2x")
    end.html_safe
  end


  def visibility_class(experience)
    return "hidden" if experience.removed?
    "visible"
  end

end

app/views/experiences/_experiences.html.erb
<div class="pull-left span8 col-md-12">
  <div class="pull-left"><h3><i class="fa fa-file-text-o fa-1x"></i>
    <span>Experience</span></h3></div>
  <div class="pull-right">
    <%= link_to '<i class="fa fa-plus"></i> Add Experience'.html_safe, new_profile_experience_path(@user), :class => 'add-experience-colorbox' %>
  </div>
</div>

<ul>
  <% @experiences.each do |experience| %>
    <li class="experience %>">
      <div class="title"><%= experience.title %></div>
      <div class="edit-link">
        <%= link_to edit_profile_experience_path(@user, experience), :class => 'edit-experience-colorbox' do  %>
          <i class="fa fa-pencil-square-o"></i>
        <% end %>
      </div>
      <div class="MB10">
        <span class="userCompany"><%= experience.company %></span>
        <span class="date"><%= experience_date(experience.start_date) %> - <%= end_date_of(experience) %> (<%= duration_for_experience(experience) %>) | <%= experience.location %></span>
      </div>
      <div class="description"><%= experience.job_description %></div>
    </li>
  <% end %>
</ul>

app/views/experiences/_form.html.erb
<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-briefcase fa-fw fa-2x"></i></span>
  <%= f.text_field :company, :spellcheck => true, :placeholder => 'Company Name', :class => "form-control" %>
  <%= error_message_on(@experience,:company) %>
</div>

<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-suitcase fa-fw fa-2x"></i></span>
  <%= f.text_field :title, :spellcheck => true, :placeholder => 'Job Title', :class => "form-control" %>
  <%= error_message_on(@experience,:title) %>
</div>

<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-map-marker fa-fw fa-2x"></i></span>
  <%= f.text_field :location, :spellcheck => true, :placeholder => 'Location', :class => "form-control" %>
  <%= error_message_on(@experience,:location) %>
</div>

<div class="field input-gruop">
  <%= label_tag :start_date %><br />
  <span class="input-group-addon"><i class="fa fa-calendar fa-fw fa-2x"></i></span>
  <%= text_field_tag 'start_date', @experience.start_date.try(:strftime, ('%m/%y')), :placeholder => 'MM/YYYY', :class => "form-control" %>
  <%= error_message_on(@experience,:start_date) %>
</div>

<div class="field input-gruop">
  <%= label_tag :end_date %><br />
  <span class="input-group-addon"><i class="fa fa-calendar fa-fw fa-2x"></i></span>
  <%= text_field_tag "end_date", @experience.end_date.try(:strftime, ('%m/%y')), :placeholder => 'MM/YYYY', :class => "form-control" %>
</div>

<%= f.hidden_field :start_date %>
<%= f.hidden_field :end_date %>

<div class="field">
  <%= f.check_box :current, :value => 1 %>
  <%= f.label :current, 'I currently work here' %><br />
</div>

<%= error_message_on(@experience,:either_end_or_current) %>
<%= error_message_on(@experience,:future_dates) %>
<%= error_message_on(@experience,:date_compatibilty) %>


<div class="field">
  <%= f.text_area :job_description, :spellcheck => true, :placeholder => 'Job Description', :class => "form-control" %>
  <%= error_message_on(@experience,:job_description) %>
</div>

<div class="field">
  <%= f.check_box :hidden %>
  <%= f.label :hidden %>
</div>

<div class="actions">
  <%= remove_experience_link if @experience.persisted? %>
  <%= colorbox_cancel_link %>
  <%= f.submit 'Update Experience',:class => "btn btn-primary btn-lg" %>
</div>

app/views/experiences/create.html.erb
<%= close_colorbox_reload_page('profile_experience') %>

app/views/experiences/destroy.html.erb
<%= close_colorbox_reload_page('profile_experience') %>

app/views/experiences/edit.html.erb
<div class="pop-up">
  <h1>Editing experience</h1>
  <%= form_for([@user, @experience], :url => profile_experience_path(@user, @experience), :method => :put) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/experiences/index.html.erb
<%= render :partial => 'experiences' %>

app/views/experiences/index.js.erb
$(".forms").html("<%= raw escape_javascript(render :partial => 'experiences/experiences') %>")
$(".add-experience-colorbox").colorbox({iframe: true, innerWidth: "50%", innerHeight: "80%"});
$(".edit-experience-colorbox").colorbox({iframe: true, innerWidth: "50%", innerHeight: "80%"});

app/views/experiences/new.html.erb
<div class="pop-up">
  <h1>Add experience</h1>
  <%= form_for([@user, @experience], :url => profile_experiences_path) do |f| %>
    <%= render :partial =>'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/experiences/remove.html.erb
<div class="edu-del">
  <h3>Are you sure you want to delete this Career/Experience</h3>
  <%= link_to 'Yes, delete', profile_experience_path(@user, @experience), :class => "btn btn-primary btn-lg", :method => :delete %>
  <%= link_to 'Cancel', edit_profile_experience_path(@user, @experience), :class => "Cancel" %>
</div>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @experience.company %>
</p>

<p>
  <b>Title:</b>
  <%= @experience.title %>
</p>

<p>
  <b>Location:</b>
  <%= @experience.location %>
</p>

<p>
  <b>Start date:</b>
  <%= @experience.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @experience.end_date %>
</p>

<p>
  <b>Job description:</b>
  <%= @experience.job_description %>
</p>

<p>
  <b>User:</b>
  <%= @experience.user_id %>
</p>


<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/update.html.erb
<%= close_colorbox_reload_page('profile_experience') %>