config/routes.rb
PocApp::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :sessions => :sessions, :confirmations => :confirmations }

  devise_scope :user do
    put "password/:scope", :to => "devise/passwords#update", :as => :update_password
    get '/password/breach/:token' => 'passwords#breach', :as => :password_breach
  end

  resources :profiles, :only => [:edit, :update, :show] do
    member do
      get :edit_image
      post :update_image
      delete :remove_avatar
    end
    resources :experiences do
      member do
        get :remove
      end
    end
    resources :certificates do
      member do
        get :remove
        delete :remove_attachment
        get :preview
      end
    end
    resources :educations do
      member do
        get :remove
      end
    end
    resources :skills, :only => [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :emails do
      member do
        post :make_primary
      end
      collection do
        get  :confirmation
        get  :breach
      end
    end
  end

  resources :suggestions, :only => [:index]
  resources :recruiters do
    collection do
      get :confirmation
    end
  end

  resources :recruiter_sessions, :only => [:new, :create]
  resources :accounts

  resources :searches
  resources :jobs
  resources :manage_pages do
    collection do
      get :require_authentication
      get :authenticate
      get :facebook
      get :redirect_from_facebook
      get :twitter
      get :twitter_callback
    end
  end

  match 'email_validation' => 'main#email_validation', :via => :get, :as => "email_validation"
  match 'social/:action', :via => :get, :to => "social#integration", :as => :social
  match 'profiles/:profile_id/:id', :via => :get, :to => "profiles#extra", :as => :profile_extra
  match 'main/:action', :via => [:get, :post], :to => "main#extra", :as => :extras
  match 'images/upload_image', :via => [:post], :to => "images#upload_image", :as => :upload_image
  match 'login', :via => [:get], :to => "main#login", :as => :login
  match 'signup', :via => [:get], :to => "main#signup", :as => :signup
  match 'forgot_password', :via => [:get], :to => "main#forgot_password", :as => :forgot_password
  match 'confirmation_instructions', :via => [:get], :to => "main#confirmation_instructions", :as => :confirmation_instructions

  get '/activities(.:format)' => 'main#activities', :as => :activities
  get '/:page' => 'main#show', :as => :page

  root :to => 'accounts#index'

end

app/models/certificate.rb
class Certificate

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :name, type: String
  field :authority, type: String
  field :month, type: String
  field :year, type: Integer
  field :user_id, type: Integer
  field :hidden, type: Boolean

  scope :removed, where(hidden: true)

  belongs_to :user

  def hide!
    self.hidden = true
    self.save
  end

  def removed?
    hidden
  end

  has_mongoid_attached_file :attachment,
                            :path => ":rails_root/public/assets/attachments/:id/:style/:basename.:extension",
                            :url  => "/assets/attachments/:id/:style/:basename.:extension"

  validates :name, :authority, :month, :year, :presence => true
  validates :year, :numericality => {:less_than_or_equal_to => 2020, :greater_than_or_equal_to => 1900}
  validates :year, :length => { :is => 4 }

  validate :current_date

  validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'application/pdf'], :message => "Please select a valid format"

  def current_date
    return if month.blank? || year.blank?
    date = DateTime.strptime([month,year].join(" "), '%B %Y')
    if date > Time.now
      errors.add(:current_date, "Date cannot be in future")
      return false
    end
    true
  end

end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController

  layout "blank"

  before_filter :get_user

  def index
    @certificates = @user.certificates

    respond_to do |format|
      format.html
      format.json { render json: @certificates }
      format.js
    end
  end

  def show
    @certificate = Certificate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @certificate }
    end
  end

  def new
    @certificate = Certificate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @certificate }
    end
  end

  def edit
    @certificate = Certificate.find(params[:id])
  end

  def create
    @certificate = Certificate.new(params[:certificate])
    @certificate.user_id = params.delete(:profile_id)
    respond_to do |format|
      if @certificate.save
        format.html
        format.json { render json: @certificate, status: :created, location: @certificate }
      else
        format.html { render action: "new" }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @certificate = Certificate.find(params[:id])
    @certificate.user_id = params.delete(:profile_id)
    respond_to do |format|
      if @certificate.update_attributes(params[:certificate])
        format.html
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @certificate = Certificate.find(params[:id])
    @certificate.destroy

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  def remove
    @certificate = Certificate.find(params[:id])
  end

  def remove_attachment
    @certificate = Certificate.find(params[:id])
    @certificate.attachment.clear
    @certificate.save
  end

  def preview
    @certificate = Certificate.find(params[:id])
  end

  private

  def get_user
    @user = User.find params[:profile_id]
    return redirect_to root_path, :alert => "Unauthorized access" unless @user == current_user
  end

end

app/helpers/certificates_helper.rb
module CertificatesHelper

  def link_to_preview(certificate)
    return if certificate.attachment.blank?
    content_tag :div, :class => "preview-link" do
      link_to preview_profile_certificate_path(@user, certificate), :class => "colorbox", :id => "certificate_#{certificate.id}" do
        image_tag ["icons/",certificate.attachment.content_type.urlize, ".png"].join
      end
    end
  end

end

app/views/certificates/_certificate.html.erb
<li class="certificate">
  <div class="title"><%= certificate.name %></div>
  <div class="edit-certificate-link">
    <%= link_to edit_profile_certificate_path(@user, certificate), :class => "edit-certificate-colorbox" do  %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>
  </div>
  <div class="pull-left">
    <span class="userCompany"><%= certificate.authority %></span>
    <div class="date">
      <%= certificate.month %> <%= certificate.year %> - Present
    </div>
  </div>
  <div class="pull-right"><%= link_to_preview(certificate) %></div>
</li>

app/views/certificates/_certificates.html.erb
<div class="pull-left span8 col-md-12">
  <div class="pull-left"><h3><i class="fa fa-certificate fa-1x"></i>
    <psan>Certificates</span></h3></div>
  <div class="pull-right">
    <%= link_to '<i class="fa fa-plus"></i> Add Certificate'.html_safe, new_profile_certificate_path(@user), :class => 'add-certificate-colorbox' %>
  </div>
</div>

<ul class="col-md-12">
  <% @certificates.each do |certificate| %>
    <%= render :partial => "certificate", :locals => {:certificate => certificate} %>
  <% end %>
</ul>

app/views/certificates/_form.html.erb
<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-briefcase fa-fw fa-2x"></i></span>
  <%= f.text_field :name, :placeholder => "Certification Name", :class => "form-control" %>
  <%= error_message_on(@certificate,:name) %>
</div>

<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-briefcase fa-fw fa-2x"></i></span>
  <%= f.text_field :authority, :placeholder => "Certification Authority", :class => "form-control" %>
  <%= error_message_on(@certificate,:name) %>
</div>

<div class="field input-gruop date">
  <%= f.select :month, options_for_select(month_names, @certificate.month), :include_blank => "Month" %>
  <%= error_message_on(@certificate,:month) %>
  <%= f.text_field :year, :placeholder => "Year", :maxlength => '4', :class => "form-control" %> 
  <span>--- Present</span>
  <%= error_message_on(@certificate,:year) %>
  <%= error_message_on(@certificate,:current_date) %>
</div>

<div class="field">
   <% if @certificate.persisted? && @certificate.attachment.present? %>
      <i class="fa fa-upload"></i>
      <div class="formRight"><%= File.basename(@certificate.attachment.url.split("?").first) %>
      <%= link_to "X", remove_attachment_profile_certificate_path(@user, @certificate), :method => :delete, :confirmation => "Are you sure?" %>
   <% else %>
     <%= f.label :attachment, :id => "certificate-attachment" do %>
      <i class="fa fa-upload"></i> <span>Upload Certificate</span>
     <% end %>
     <%= f.file_field :attachment, :style => "display:none;" %>
     <%= error_message_on(@certificate,:attachment) %>
     <div class="formError"></div>
   <% end %>
</div>

<div class="field">
  <%= f.check_box :hidden %>
  <%= f.label :hidden %>
</div>

<div class="actions">
  <%= remove_certificate_link if @certificate.persisted? %>
  <%= colorbox_cancel_link %>
  <%= f.submit "Add", :class => "btn btn-primary btn-lg" %>
</div>

app/views/certificates/create.html.erb
<%= close_colorbox_reload_page("profile_certificate") %>

app/views/certificates/destroy.html.erb
<%= close_colorbox_reload_page("profile_certificate") %>

app/views/certificates/edit.html.erb
<div class="pop-up">
  <h1>Editing certificate</h1>
  <%= form_for([@user, @certificate], :html => {:multipart => true}, :url => profile_certificate_path(@user, @certificate)) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/certificates/index.html.erb
<%= render :partial => "certificates" %>

app/views/certificates/index.js.erb
$(".forms").html("<%= raw escape_javascript(render :partial => 'certificates/certificates') %>")
$(".add-certificate-colorbox").colorbox({iframe: true, innerWidth: "50%", innerHeight: "50%"});
$(".edit-certificate-colorbox").colorbox({iframe: true, innerWidth: "50%", innerHeight: "50%"});
$(".colorbox").colorbox()

app/views/certificates/new.html.erb
<div class="pop-up">
  <h1>Add Certificate</h1>
  <%= form_for([@user, @certificate], :html => {:multipart => true}, :url => profile_certificates_path) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/certificates/preview.html.erb
<div style="float:left;text-align:center;">
  <iframe id="viewer" src ="<%= @certificate.attachment.url %>" width="850" height="1024"></iframe>
</div>

app/views/certificates/remove.html.erb
<div class="edu-del">
	<h3>Are you sure you want to delete this Certificate</h3>
  <%= link_to "Yes, delete", profile_certificate_path(@user, @certificate), :class => "btn btn-primary btn-lg", :method => :delete %>
  <%= link_to "Cancel", edit_profile_certificate_path(@user, @certificate), :class => "Cancel" %>
</div>

app/views/certificates/remove_attachment.html.erb
<%= close_colorbox_reload_page("profile_certificate") %>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @certificate.name %>
</p>

<p>
  <b>Authority:</b>
  <%= @certificate.authority %>
</p>

<p>
  <b>Month:</b>
  <%= @certificate.month %>
</p>

<p>
  <b>Year:</b>
  <%= @certificate.year %>
</p>


<%= link_to 'Edit', edit_certificate_path(@certificate) %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/update.html.erb
<%= close_colorbox_reload_page("profile_certificate") %>