config/routes.rb
PocApp::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :sessions => :sessions, :confirmations => :confirmations }

  devise_scope :user do
    put "password/:scope", :to => "devise/passwords#update", :as => :update_password
    get '/password/breach/:token' => 'passwords#breach', :as => :password_breach
  end

  resources :profiles, :only => [:edit, :update, :show] do
    member do
      get :edit_image
      post :update_image
      delete :remove_avatar
    end
    resources :experiences do
      member do
        get :remove
      end
    end
    resources :certificates do
      member do
        get :remove
        delete :remove_attachment
        get :preview
      end
    end
    resources :educations do
      member do
        get :remove
      end
    end
    resources :skills, :only => [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :emails do
      member do
        post :make_primary
      end
      collection do
        get  :confirmation
        get  :breach
      end
    end
  end

  resources :suggestions, :only => [:index]
  resources :recruiters do
    collection do
      get :confirmation
    end
  end

  resources :recruiter_sessions, :only => [:new, :create]
  resources :accounts

  resources :searches
  resources :jobs
  resources :manage_pages do
    collection do
      get :require_authentication
      get :authenticate
      get :facebook
      get :redirect_from_facebook
      get :twitter
      get :twitter_callback
    end
  end

  match 'email_validation' => 'main#email_validation', :via => :get, :as => "email_validation"
  match 'social/:action', :via => :get, :to => "social#integration", :as => :social
  match 'profiles/:profile_id/:id', :via => :get, :to => "profiles#extra", :as => :profile_extra
  match 'main/:action', :via => [:get, :post], :to => "main#extra", :as => :extras
  match 'images/upload_image', :via => [:post], :to => "images#upload_image", :as => :upload_image
  match 'login', :via => [:get], :to => "main#login", :as => :login
  match 'signup', :via => [:get], :to => "main#signup", :as => :signup
  match 'forgot_password', :via => [:get], :to => "main#forgot_password", :as => :forgot_password
  match 'confirmation_instructions', :via => [:get], :to => "main#confirmation_instructions", :as => :confirmation_instructions

  get '/activities(.:format)' => 'main#activities', :as => :activities
  get '/:page' => 'main#show', :as => :page

  root :to => 'accounts#index'

end

app/helpers/educations_helper.rb
module EducationsHelper

  def enrollment_year_range
    (1900..Time.now.year).to_a
  end

  def graduation_year_range
    (1900..2020).to_a
  end

end

app/views/educations/_educations.html.erb
<div class="pull-left span8 col-md-12">
  <div class="pull-left"><h3><i class="fa fa-book fa-1x"></i>
    <span>Education</span></h3></div>
  <div class="pull-right">
    <%= link_to '<i class="fa fa-plus"></i> Add Education'.html_safe, new_profile_education_path(@user), :class => 'add-education-colorbox' %>
  </div>
</div>

<ul>
  <% @educations.each do |education| %>
    <li class="education">
      <div class="title"><%= education.school %></div>
      <div class="edit-education-link">
        <%= link_to edit_profile_education_path(@user, education), :class => "edit-education-colorbox" do  %>
          <i class="fa fa-pencil-square-o"></i>
        <% end %>
      </div>
      <div><span class="userCompany"><%= education.degree %></span></div>
      <div class="date"><span><%= education.enrollment_year %></span> - <span><%= education.graduation_year %></span></div>
    </li>
  <% end %>
</ul>

app/views/educations/_form.html.erb
<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-briefcase fa-fw fa-2x"></i></span>
  <%= f.text_field :school, :placeholder => "School", :class => "form-control" %>
  <%= error_message_on(@education,:school) %>
</div>

<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-briefcase fa-fw fa-2x"></i></span>
  <%= year_select(f, :name => :enrollment_year, :select_options => enrollment_year_range, :blank_text => "Enrolment Year" ) %>
    ___
    <%= year_select(f, :name => :graduation_year, :select_options => graduation_year_range, :blank_text => "Graduation Year") %>
  <%= error_message_on(@education,:enrollment_year) %>
  <%= error_message_on(@education,:graduation_year_limit) %>
</div>

<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-briefcase fa-fw fa-2x"></i></span>
  <%= f.text_field :degree, :placeholder => "Degree", :class => "form-control" %>
  <%= error_message_on(@education,:degree) %>
</div>

<div class="field input-gruop">
  <span class="input-group-addon"><i class="fa fa-briefcase fa-fw fa-2x"></i></span>
  <%= f.text_field :grade, :placeholder => "Grade", :class => "form-control" %>
  <%= error_message_on(@education,:grade) %>
</div>

<div class="field">
  <%= f.check_box :hidden %>
  <%= f.label :hidden %>
</div>

<div class="actions">
  <%= remove_education_link if @education.persisted? %>
  <%= colorbox_cancel_link %>
  <%= f.submit 'Create Education',:class => "btn btn-primary btn-lg" %>
</div>

app/views/educations/create.html.erb
<%= close_colorbox_reload_page("profile_education") %>

app/views/educations/destroy.html.erb
<%= close_colorbox_reload_page("profile_education") %>

app/views/educations/edit.html.erb
<div class="pop-up">
  <h1>Editing education</h1>
  <%= form_for([@user, @education], :url => profile_education_path(@user, @education)) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/educations/index.html.erb
<%= render "educations" %>

app/views/educations/index.js.erb
$(".forms").html("<%= raw escape_javascript(render :partial => 'educations/educations') %>")
$(".add-education-colorbox").colorbox({iframe: true, innerWidth: "50%", innerHeight: "55%"});
$(".edit-education-colorbox").colorbox({iframe: true, innerWidth: "50%", innerHeight: "55%"});

app/views/educations/new.html.erb
<div class="pop-up">
  <h1>Add Education</h1>
  <%= form_for([@user, @education], :url => profile_educations_path) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/educations/remove.html.erb
<div class="edu-del">
	<h3>Are you sure you want to delete this Education</h3>
  <%= link_to "Yes, delete", profile_education_path(@user, @education), :class => "btn btn-primary btn-lg", :method => :delete %>
  <%= link_to "Cancel",  edit_profile_education_path(@user, @education), :class => "Cancel" %>
</div>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>School:</b>
  <%= @education.school %>
</p>

<p>
  <b>Enrollment year:</b>
  <%= @education.enrollment_year %>
</p>

<p>
  <b>Graduation year:</b>
  <%= @education.graduation_year %>
</p>

<p>
  <b>Degree:</b>
  <%= @education.degree %>
</p>

<p>
  <b>Grade:</b>
  <%= @education.grade %>
</p>


<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>

app/views/educations/update.html.erb
<%= close_colorbox_reload_page("profile_education") %>